# Generated by Django 2.2.28 on 2025-03-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('MenuID', models.AutoField(primary_key=True, serialize=False)),
                ('MenuName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=16, unique=True)),
                ('firstName', models.CharField(max_length=16)),
                ('surname', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=16)),
                ('profilePicture', models.ImageField(blank=True, upload_to='profile_images')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('ReviewID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=30)),
                ('RatingNum', models.IntegerField()),
                ('ReviewText', models.CharField(max_length=1000)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_by_Username', to='BookaBite.User', to_field='Username')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=30)),
                ('ItemPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ItemDesc', models.CharField(max_length=100)),
                ('SpiceLevel', models.IntegerField()),
                ('MenuName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookaBite.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('bookingDate', models.DateField()),
                ('bookingTime', models.TimeField()),
                ('partyMembers', models.IntegerField()),
                ('surname', models.CharField(max_length=16)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_by_email', to='BookaBite.User', to_field='email')),
            ],
        ),
    ]
