# Generated by Django 2.2.28 on 2025-03-21 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookaBite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=16, unique=True)),
                ('firstName', models.CharField(max_length=16)),
                ('surname', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=16)),
                ('profilePicture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='bookings',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_by_email', to='BookaBite.UserProfile', to_field='email'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='Username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_by_Username', to='BookaBite.UserProfile', to_field='Username'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
